"""Removing the image file column

Revision ID: f8a3aacac0cf
Revises: 7860c81bd2a5
Create Date: 2024-04-22 08:29:32.181807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a3aacac0cf'
down_revision = '7860c81bd2a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
